export enum CAR_BALANCE_TYPE {
	FAN = 'FAN',
	DRIFT = 'DRIFT',
	SPEED = 'SPEED',
}

export enum CAR_CONTROLS_IDS {
	FORWARD = 'FORWARD',
	FORWARD_BOOST = 'FORWARD_BOOST',
	REVERS = 'REVERS',
	LEFT = 'LEFT',
	RIGHT = 'RIGHT',
	BRAKE = 'BRAKE',
	RESPAWN = 'RESPAWN',
}
